### ISSUE TITLE
Anisotropic kernels

### ISSUE THREAD

**Issue by RodrigoAVargasHdz** [dfm/tinygp#27] opened 2022-01-21 20:30 UTC
Hi
I was wondering if you could give me some tips on how to properly create an anisotropic kernel.
When I used,   
```
params = {
            "theta_c": jnp.ones(1),
            "theta_k": jnp.ones(d),  # d ---> number of features in x
  }
``` 
and the kernel 
`kernel = params["theta_c"] ** 2 * kernels.ExpSquared(params["theta_k"])`

I get the following error,
**UnfilteredStackTrace: TypeError: triangular_solve requires the last two dimensions of a to be equal in size, got a.shape of (10, 10, 1).**

However, if I change the parameters to 
```
params = {
            "theta_c": 1.,
            "theta_k":1., 
}
```

With this kernel's parameters definition, `tinygp` works properly.

I used your GettingStarted tutorial as reference code, the only difference is that my toy training data is (10,15). 

Thanks :)

**Comment by dfm** [comment] 2022-01-21 20:38
Can you share a [full minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this error, as well as what version of all the packages you have (python, jax, tinygp, etc.). Then it'll be easier for me to make recommendations. Thanks!

**Comment by dfm** [comment] 2022-01-21 21:10
From a quick look, I expect that the following would work:

```python
params = {
            "theta_c": jnp.ones(()),
            "theta_k": jnp.ones(d),
}
```

because your version was doing some strange broadcasting. This is almost certainly a bug, so I'll look into that, but my suggestion here should probably work. If not, please post a more complete example as I described above.

**Comment by RodrigoAVargasHdz** [comment] 2022-01-21 23:05
Hi,

It seems that your tip made it work, however, when I tried `kernel.Matern32` and `kernel.Matern52` I get a NAN in the neg-MLL. 
I decided to put the code on a google collab so you can check it :)
https://colab.research.google.com/drive/151TL_19PrqZIyo7tDmVOuu-j7zFb1hVd?usp=sharing

Thanks for the help!

**Comment by dfm** [comment] 2022-01-22 01:27
That link doesn't seem publicly available - can you try [gist.github.com](https://gist.github.com/) or something instead?

I expect that you might need to enable double precision if you haven't already:

```python
from jax.config import config
config.update("jax_enable_x64", True)
```

**Comment by RodrigoAVargasHdz** [comment] 2022-01-22 15:36
Sorry, I thought I made the changes to "public".
This new link should work! 
https://colab.research.google.com/drive/151TL_19PrqZIyo7tDmVOuu-j7zFb1hVd?usp=sharing

My code already includes that config flag

**Comment by dfm** [comment] 2022-01-22 15:57
I see it now, but that definitely isn't a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)! For example, it depends on data on your google drive and has a lot of excess code not related to this issue. Please look at the linked document and try to isolate the issue.

**Comment by RodrigoAVargasHdz** [comment] 2022-01-22 16:52
I clean the collab, however, all the "extra" code is simply reading data. I am using a 15-D data set since it was the only one I had quick access to that has more than one feature. 

I copy-paste the same code
[<script src="https://gist.github.com/RodrigoAVargasHdz/3c4d91b50a3e377df08807b9426e2a41.js"></script>](https://gist.github.com/RodrigoAVargasHdz/3c4d91b50a3e377df08807b9426e2a41)

hope this helps and thanks :)

**Comment by dfm** [comment] 2022-01-22 17:17
That doesn't help! I still can't execute the code and I'm sorry but I can't help you debug if you don't take the time to isolate the problem.

**Comment by RodrigoAVargasHdz** [comment] 2022-01-22 23:09
I uploaded the code with the Data in a Github repo.

https://github.com/RodrigoAVargasHdz/tinygp_test.git

May be helpful since that is exactly the code I am running. 

Again thanks for the help!

**Comment by dfm** [comment] 2022-01-24 06:52
The code you've shared continues depend on loading your binary data files, a bunch of data pre-processing, and you haven't even isolated where the issue is occurring. I'm glad that you want to use this code, but I'm volunteering my time here and I don't have the capacity to figure out where the issues are coming from in _your_ code as well as mine. I'm going to close this for now and if you want to re-open it with a [*MINIMAL* reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) (as I have now linked to for the 3rd time) then I'll be happy to have another go.

**Closed by dfm** 2022-01-24 06:52 UTC
Labels: bug

**Comment by RodrigoAVargasHdz** [comment] 2022-01-24 16:23
I cleaned the Google collab trying to avoid reading/processing data.

[Collab](https://colab.research.google.com/drive/151TL_19PrqZIyo7tDmVOuu-j7zFb1hVd?usp=sharing)

As an example, I used the Hartmann 6-D function (https://www.sfu.ca/~ssurjano/hart6.html)
Still, for this new example, your GP code gives me a problem when any `Matern` kernel is used; the `RBF` works fine.

Thanks for your time :)

**Comment by dfm** [comment] 2022-01-24 16:51
That's better - you still didn't isolate the issue (e.g. there's no need to optimize, so why require jaxopt as a dependency), but at least I could run the code now.

The issue is that your initial kernel parameters are nonsensical wrt to your input data. Your initial length scales are >an order of magnitude larger than the range of your input data, which means that your initial covariance matrix is just a constant. This is not a valid GP model, so it's correct for the model to return nan or -inf (which is what it'll do on the `main` branch). You're going to need to choose more sensible parameters on the scale of your input data (e.g. `ones` works fine in your test case)!

Another point: you might want to either put bounds on your parameters or optimize in the log, because it doesn't really make sense for length scales and amplitudes to go negative.

**Comment by RodrigoAVargasHdz** [comment] 2022-01-25 00:14
Sorry to keep bothering you. 
Why should the optimal parameters of `Mater52` and `RBF` be that different? 
I managed to run` L-BFGS-B `using `JaxOpt` when the bounds are `(0.1,0.85)` the optimization for `Mater52` works without a problem but for any larger upper bound, for example `(0.1,0.9)`, I get the same `NAN` error during the Cholesky decomposition. Also when I set the bounds to `(0.1,0.85)` the "optimal length scale" parameters are set to `0.85`

`initial params: {'theta_c': DeviceArray([0.35482928], dtype=float64), 'theta_k': DeviceArray([0.42307813, 0.57885954, 0.41825036, 0.57688042, 0.72303935,
             0.25424031], dtype=float64)}
Initial negative log likelihood: 368.8367012704128
optimal params: OptStep(params={'theta_c': DeviceArray([0.52406465], dtype=float64), 'theta_k': DeviceArray([0.85, 0.85, 0.85, 0.85, 0.85, 0.85], dtype=float64)}, state=ScipyMinimizeInfo(fun_val=DeviceArray(40.99598537, dtype=float64), success=True, status=0, iter_num=5))
Optimal negative log likelihood: 40.99598536673935`
